# Generated by Django 5.2.12 on 2026-03-31 01:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_normalized', models.CharField(db_index=True, editable=False, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], db_index=True, default='open', max_length=20)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='features.featurerequest')),
            ],
            options={
                'db_table': 'feature_requests',
                'ordering': ['-vote_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='features.featurerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['-vote_count', '-created_at'], name='idx_ranking'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['-created_at'], name='idx_newest'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['author'], name='idx_author'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['feature_request'], name='idx_vote_feature'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='idx_vote_user'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'feature_request'), name='unique_vote_per_user_feature'),
        ),
    ]
